name: grounded
description: An app for parents built by parents

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 1.12.0
  firebase_auth: 3.3.6
  cloud_firestore: 3.1.7
  firebase_messaging: 11.2.6
  firebase_database: 9.0.6
  firebase_storage: 10.2.6

  shared_preferences: 2.0.12
  json_annotation: 4.4.0
  uuid: 3.0.5
  flutter_easyloading: 3.0.3
  flutter_svg: 1.0.3
  adaptive_dialog: 1.3.0
  image_picker: 0.8.4+5
  charts_flutter: 0.12.0
  url_launcher: 6.0.12
  dart_date: 1.1.1
  carousel_slider: 4.0.0
  dots_indicator: 2.1.0
  open_mail_app: 0.4.4
  percent_indicator: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.0
  build_runner: 2.1.7
  json_serializable: 6.1.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"

flutter_launcher_name:
  name: "Grounded"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/intro/
    - assets/images/questions/
    - assets/data/

  fonts:
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
