name: Android App Build

on:
  push:
    branches:
      - master

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.0"
          channel: "stable"

      - name: Download Flutter Packages
        run: flutter pub get

      - name: Fix formatting issues if any
        run: flutter format --set-exit-if-changed .

      - name: Build APK
        run: flutter build apk

      # Upload generated apk to the artifacts.
      # - name: Store APK in repo
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/apk/release/app-release.apk

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
          commit: master
          tag: v1.0.${{ github.run_number }}
