name: iOS App Build

on:
  push:
    branches:
      - master

jobs:
  deploy_ios:
    name: Deploy iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup xCode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.2"

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.0"
          channel: "stable"

      - name: Download Flutter Packages
        run: flutter pub get

      - name: Fix formatting issues if any
        run: flutter format --set-exit-if-changed .

      - name: Build and Archive iOS Build
        run: flutter build ios --release --no-codesign

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: ios
        env:
          APP_STORE_CONNECT_TEAM_ID: "${{ secrets.APP_STORE_CONNECT_TEAM_ID }}"
          DEVELOPER_APP_ID: "${{ secrets.DEVELOPER_APP_ID }}"
          DEVELOPER_APP_IDENTIFIER: "${{ secrets.DEVELOPER_APP_IDENTIFIER }}"
          DEVELOPER_PORTAL_TEAM_ID: "${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}"
          FASTLANE_APPLE_ID: "${{ secrets.FASTLANE_APPLE_ID }}"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}"
          MATCH_PASSWORD: "${{ secrets.MATCH_PASSWORD }}"
          GIT_AUTHORIZATION: "${{ secrets.GIT_AUTHORIZATION }}"
          PROVISIONING_PROFILE_SPECIFIER: "${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}"
          TEMP_KEYCHAIN_PASSWORD: "${{ secrets.TEMP_KEYCHAIN_PASSWORD }}"
          TEMP_KEYCHAIN_USER: "${{ secrets.TEMP_KEYCHAIN_USER }}"
